name: offline_localization
description: "A Offline Localization tool for simple Localisations using CSV files."
version: 1.0.0
homepage: "https://github.com/SujalChoudhari/offline_localization"

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0